server:
  port: 8090

spring:
#  h2:                              # ram da çalışan bir database kullanmak istersek (proje ile çalışan proje kapanınca sıfırlanan)
#    console:
#      enabled: true
  datasource:
    username: postgres
    password: root
#    url: jdbc:postgresql://localhost:5532/MovieDb   # dockerdaki postgresi çalıştırsın diye 5532
    url: jdbc:postgresql://localhost:5532/dockerDenemeDb # bu veritabanını dockerdaki terminalden kuracağız.
                                                         # bunun için dockerda çalışan postgres konteynırında terminale gir
                                                         # su postgres  komutu ile postgres kullanıcı yetkisini al
                                                         # createdb dockerDenemeDb komutu ile veritabanını oluştur.
                                                         # bilgisayarında bu veritabanı oluşturulmuş olacak.
                                                         # bu yöntemle pgadmine girmeden docker ile veritabanı oluşturulabilir
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update